import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { launch, connect, closeSession, getMiniProgram, isConnected, getCurrentPage } from './session.js';
import { buildSnapshot } from '../snapshot/builder.js';
import { resolveRef, resolveRefFull } from '../snapshot/refs.js';
import { startRecording, stopRecording, recordAction, isRecording } from '../replay/recorder.js';

const DEFAULT_PORT = 9430;
const STATE_DIR = path.join(os.homedir(), '.agent-miniprogram');
const PID_FILE = path.join(STATE_DIR, 'daemon.pid');

function ensureStateDir() {
  if (!fs.existsSync(STATE_DIR)) {
    fs.mkdirSync(STATE_DIR, { recursive: true });
  }
}

const RECORDABLE_METHODS = new Set(['tap', 'input', 'scroll', 'longPress', 'swipe', 'navigate', 'back', 'wait']);

// Built-in WXML tags that are NOT custom components.
// Any tag not in this set is treated as a custom component boundary.
const BUILT_IN_WXML_TAGS = new Set([
  'view', 'scroll-view', 'swiper', 'swiper-item', 'movable-view', 'movable-area',
  'cover-view', 'cover-image', 'icon', 'text', 'rich-text', 'progress',
  'button', 'checkbox-group', 'checkbox', 'form', 'input', 'label',
  'picker', 'picker-view', 'picker-view-column', 'radio-group', 'radio',
  'slider', 'switch', 'textarea', 'navigator', 'functional-page-navigator',
  'audio', 'camera', 'image', 'live-player', 'live-pusher', 'video',
  'map', 'canvas', 'open-data', 'web-view', 'ad', 'official-account',
  'block', 'page', 'template', 'slot', 'wxs',
  'svg', 'path', 'circle', 'rect', 'line', 'polygon', 'polyline',
  'ellipse', 'g', 'defs', 'use', 'symbol',
]);

/**
 * Find the first split point in a " > "-separated selector where the automator
 * needs a context switch:
 *   1. A leading "#id" segment — page.$('#id') works but "#id > child" does not.
 *   2. A custom-component tag — element.$() must be used on the component itself.
 */
function findBoundary(selector: string): { prefix: string; suffix: string } | null {
  const parts = selector.split(' > ');
  if (parts.length < 2) return null;

  // Rule 1: leading #id — always split after it so we anchor cleanly.
  if (parts[0].startsWith('#')) {
    return { prefix: parts[0], suffix: parts.slice(1).join(' > ') };
  }

  // Rule 2: first custom-component tag in the path.
  for (let i = 0; i < parts.length - 1; i++) {
    const tag = parts[i].split(':')[0].split('.')[0].toLowerCase();
    if (!BUILT_IN_WXML_TAGS.has(tag)) {
      return {
        prefix: parts.slice(0, i + 1).join(' > '),
        suffix: parts.slice(i + 1).join(' > '),
      };
    }
  }
  return null;
}

/** Find the first element matching selector, splitting at component/ID boundaries as needed. */
async function resolveFirst(context: any, selector: string, pageCtx?: any): Promise<any> {
  const el = await context.$(selector);
  if (el) return el;

  const split = findBoundary(selector);
  if (!split) return null;

  // Get the anchor element (ID or custom component) via a simple query on its prefix.
  const anchor = await context.$(split.prefix);
  if (anchor) {
    const inner = await resolveFirst(anchor, split.suffix, pageCtx ?? context);
    if (inner) return inner;
  }

  // Fallback: slot content lives in the parent (page) scope, not inside the anchor.
  // Skip the prefix and try the suffix directly from the page context.
  const root = pageCtx ?? context;
  if (root !== context || !anchor) {
    return resolveFirst(root, split.suffix, root);
  }

  return null;
}

/** Find all elements matching selector inside the innermost scope, for matchIndex resolution. */
async function resolveAll(context: any, selector: string, pageCtx?: any): Promise<any[]> {
  const els = await context.$$(selector);
  if (els?.length) return els;

  const split = findBoundary(selector);
  if (!split) return [];

  const anchor = await context.$(split.prefix);
  if (anchor) {
    const inner = await resolveAll(anchor, split.suffix, pageCtx ?? context);
    if (inner?.length) return inner;
  }

  // Fallback: try suffix from page context (slot content case).
  const root = pageCtx ?? context;
  if (root !== context || !anchor) {
    return resolveAll(root, split.suffix, root);
  }

  return [];
}

/**
 * Resolve a @ref or raw selector to an automator Element.
 * Handles CSS selectors generated by snapshot/builder, including those that
 * cross custom component boundaries.
 */
async function resolveElement(page: any, refOrSelector: string): Promise<any> {
  const full = resolveRefFull(refOrSelector);
  const selector = full?.selector ?? refOrSelector;
  const matchIndex = full?.matchIndex ?? 0;

  if (matchIndex > 0) {
    const els = await resolveAll(page, selector);
    return els?.[matchIndex] ?? null;
  }

  return resolveFirst(page, selector);
}

async function handleRpc(method: string, params: any): Promise<any> {
  const mp = getMiniProgram();

  // Record actions if recording is active
  if (isRecording() && RECORDABLE_METHODS.has(method)) {
    recordAction(method, params);
  }

  switch (method) {
    case 'launch': {
      await launch(params.projectPath, params.wsEndpoint);
      return { ok: true };
    }

    case 'connect': {
      await connect(params.wsEndpoint || 'ws://localhost:9420');
      return { ok: true };
    }

    case 'close': {
      await closeSession();
      return { ok: true };
    }

    case 'status': {
      return {
        connected: isConnected(),
        currentPage: await getCurrentPage(),
      };
    }

    case 'snapshot': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const snapshot = await buildSnapshot(page, { includeData: params.data });
      return { snapshot };
    }

    case 'screenshot': {
      if (!mp) throw new Error('Not connected');
      const savePath = params.path || path.join(STATE_DIR, 'screenshot.png');
      await mp.screenshot({ path: savePath });
      return { path: savePath };
    }

    case 'navigate': {
      if (!mp) throw new Error('Not connected');
      const type = params.type || 'navigateTo';
      if (type === 'switchTab') {
        await mp.switchTab(params.url);
      } else if (type === 'reLaunch') {
        await mp.reLaunch(params.url);
      } else {
        await mp.navigateTo(params.url);
      }
      return { ok: true, url: params.url };
    }

    case 'back': {
      if (!mp) throw new Error('Not connected');
      await mp.navigateBack();
      return { ok: true };
    }

    case 'tap': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      await el.tap();
      return { ok: true };
    }

    case 'input': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      await el.input(params.text);
      return { ok: true };
    }

    case 'scroll': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      await el.scrollTo(params.x || 0, params.y || 0);
      return { ok: true };
    }

    case 'longPress': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      await el.longpress();
      return { ok: true };
    }

    case 'swipe': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      const rect = await el.offset();
      const cx = rect.left + rect.width / 2;
      const cy = rect.top + rect.height / 2;
      const dist = 150;
      const dirMap: Record<string, [number, number, number, number]> = {
        up: [cx, cy + dist, cx, cy - dist],
        down: [cx, cy - dist, cx, cy + dist],
        left: [cx + dist, cy, cx - dist, cy],
        right: [cx - dist, cy, cx + dist, cy],
      };
      const [x1, y1, x2, y2] = dirMap[params.direction] ?? ([cx, cy, cx, cy] as [number, number, number, number]);
      await page.callMethod('__swipe__', x1, y1, x2, y2);
      return { ok: true };
    }

    case 'wait': {
      if (!mp) throw new Error('Not connected');
      if (typeof params.ms === 'number') {
        await new Promise(r => setTimeout(r, params.ms));
        return { ok: true };
      }
      if (params.selector || params.ref) {
        const page = await mp.currentPage();
        const selector = resolveRef(params.ref) ?? params.ref ?? params.selector;
        await page.waitFor(selector);
        return { ok: true };
      }
      if (params.text) {
        const page = await mp.currentPage();
        await page.waitFor(params.text);
        return { ok: true };
      }
      throw new Error('wait: specify ms, ref/selector, or text');
    }

    case 'data': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const data = await page.data();
      if (params.path) {
        const parts = params.path.split('.');
        let val: any = data;
        for (const part of parts) {
          val = val?.[part];
        }
        return { data: val };
      }
      return { data };
    }

    case 'eval': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const result = await page.evaluate(params.code);
      return { result };
    }

    case 'mock': {
      if (!mp) throw new Error('Not connected');
      await mp.mockWxMethod(params.api, params.response);
      return { ok: true };
    }

    case 'diff': {
      if (!mp) throw new Error('Not connected');
      const prevFile = path.join(STATE_DIR, 'last-snapshot.txt');
      const prev = fs.existsSync(prevFile) ? fs.readFileSync(prevFile, 'utf-8') : '';
      const page = await mp.currentPage();
      const current = await buildSnapshot(page, {});
      const diff = computeDiff(prev, current.snapshot);
      fs.writeFileSync(prevFile, current.snapshot);
      return { diff, current: current.snapshot };
    }

    case 'recordStart': {
      startRecording();
      return { ok: true };
    }

    case 'recordStop': {
      const outPath = stopRecording(params.output);
      return { ok: true, path: outPath };
    }

    default:
      throw new Error(`Unknown method: ${method}`);
  }
}

function computeDiff(a: string, b: string): string {
  const aLines = a.split('\n');
  const bLines = b.split('\n');
  const added = bLines.filter(l => !aLines.includes(l)).map(l => `+ ${l}`);
  const removed = aLines.filter(l => !bLines.includes(l)).map(l => `- ${l}`);
  if (added.length === 0 && removed.length === 0) return '(no changes)';
  return [...removed, ...added].join('\n');
}

function startServer(port: number) {
  ensureStateDir();

  const server = http.createServer(async (req, res) => {
    if (req.method !== 'POST' || req.url !== '/rpc') {
      res.writeHead(404);
      res.end('Not found');
      return;
    }

    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', async () => {
      let parsed: any;
      try {
        parsed = JSON.parse(body);
      } catch {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Invalid JSON' }));
        return;
      }

      const { method, params = {} } = parsed;
      try {
        const result = await handleRpc(method, params);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ result }));
      } catch (err: any) {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: err.message || String(err) }));
      }
    });
  });

  server.listen(port, '127.0.0.1', () => {
    fs.writeFileSync(PID_FILE, String(process.pid));
    console.log(`agent-mp daemon running on http://127.0.0.1:${port}`);
  });

  process.on('SIGTERM', () => {
    server.close();
    if (fs.existsSync(PID_FILE)) fs.unlinkSync(PID_FILE);
    process.exit(0);
  });

  process.on('SIGINT', () => {
    server.close();
    if (fs.existsSync(PID_FILE)) fs.unlinkSync(PID_FILE);
    process.exit(0);
  });
}

const port = parseInt(process.env.AGENT_MP_PORT || String(DEFAULT_PORT), 10);
startServer(port);
