import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { launch, connect, closeSession, getMiniProgram, isConnected, getCurrentPage } from './session.js';
import { buildSnapshot } from '../snapshot/builder.js';
import { resolveRef } from '../snapshot/refs.js';
import { startRecording, stopRecording, recordAction, isRecording } from '../replay/recorder.js';

const DEFAULT_PORT = 9430;
const STATE_DIR = path.join(os.homedir(), '.agent-miniprogram');
const PID_FILE = path.join(STATE_DIR, 'daemon.pid');

function ensureStateDir() {
  if (!fs.existsSync(STATE_DIR)) {
    fs.mkdirSync(STATE_DIR, { recursive: true });
  }
}

const RECORDABLE_METHODS = new Set(['tap', 'input', 'scroll', 'longPress', 'swipe', 'navigate', 'back', 'wait']);

/**
 * Resolve a @ref or raw selector to an automator Element.
 * Handles CSS selectors generated by snapshot/builder (e.g. "page > view.container > button:nth-child(2)").
 */
async function resolveElement(page: any, refOrSelector: string): Promise<any> {
  const selector = resolveRef(refOrSelector) ?? refOrSelector;
  const el = await page.$(selector);
  if (el) return el;
  // Fallback: if selector starts with "page > ", strip that prefix and try again
  if (selector.startsWith('page > ')) {
    const trimmed = selector.slice('page > '.length);
    return await page.$(trimmed);
  }
  return null;
}

async function handleRpc(method: string, params: any): Promise<any> {
  const mp = getMiniProgram();

  // Record actions if recording is active
  if (isRecording() && RECORDABLE_METHODS.has(method)) {
    recordAction(method, params);
  }

  switch (method) {
    case 'launch': {
      await launch(params.projectPath, params.wsEndpoint);
      return { ok: true };
    }

    case 'connect': {
      await connect(params.wsEndpoint || 'ws://localhost:9420');
      return { ok: true };
    }

    case 'close': {
      await closeSession();
      return { ok: true };
    }

    case 'status': {
      return {
        connected: isConnected(),
        currentPage: await getCurrentPage(),
      };
    }

    case 'snapshot': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const snapshot = await buildSnapshot(page, { includeData: params.data });
      return { snapshot };
    }

    case 'screenshot': {
      if (!mp) throw new Error('Not connected');
      const savePath = params.path || path.join(STATE_DIR, 'screenshot.png');
      await mp.screenshot({ path: savePath });
      return { path: savePath };
    }

    case 'navigate': {
      if (!mp) throw new Error('Not connected');
      const type = params.type || 'navigateTo';
      await mp.navigateTo({ url: params.url });
      return { ok: true, url: params.url };
    }

    case 'back': {
      if (!mp) throw new Error('Not connected');
      await mp.navigateBack();
      return { ok: true };
    }

    case 'tap': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      await el.tap();
      return { ok: true };
    }

    case 'input': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      await el.input(params.text);
      return { ok: true };
    }

    case 'scroll': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      await el.scrollTo(params.x || 0, params.y || 0);
      return { ok: true };
    }

    case 'longPress': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      await el.longpress();
      return { ok: true };
    }

    case 'swipe': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const el = await resolveElement(page, params.ref);
      if (!el) throw new Error(`Element not found: ${params.ref}`);
      const rect = await el.offset();
      const cx = rect.left + rect.width / 2;
      const cy = rect.top + rect.height / 2;
      const dist = 150;
      const dirMap: Record<string, [number, number, number, number]> = {
        up: [cx, cy + dist, cx, cy - dist],
        down: [cx, cy - dist, cx, cy + dist],
        left: [cx + dist, cy, cx - dist, cy],
        right: [cx - dist, cy, cx + dist, cy],
      };
      const [x1, y1, x2, y2] = dirMap[params.direction] ?? ([cx, cy, cx, cy] as [number, number, number, number]);
      await page.callMethod('__swipe__', x1, y1, x2, y2);
      return { ok: true };
    }

    case 'wait': {
      if (!mp) throw new Error('Not connected');
      if (typeof params.ms === 'number') {
        await new Promise(r => setTimeout(r, params.ms));
        return { ok: true };
      }
      if (params.selector || params.ref) {
        const page = await mp.currentPage();
        const selector = resolveRef(params.ref) ?? params.ref ?? params.selector;
        await page.waitFor(selector);
        return { ok: true };
      }
      if (params.text) {
        const page = await mp.currentPage();
        await page.waitFor(params.text);
        return { ok: true };
      }
      throw new Error('wait: specify ms, ref/selector, or text');
    }

    case 'data': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const data = await page.data();
      if (params.path) {
        const parts = params.path.split('.');
        let val: any = data;
        for (const part of parts) {
          val = val?.[part];
        }
        return { data: val };
      }
      return { data };
    }

    case 'eval': {
      if (!mp) throw new Error('Not connected');
      const page = await mp.currentPage();
      const result = await page.evaluate(params.code);
      return { result };
    }

    case 'mock': {
      if (!mp) throw new Error('Not connected');
      await mp.mockWxMethod(params.api, params.response);
      return { ok: true };
    }

    case 'diff': {
      if (!mp) throw new Error('Not connected');
      const prevFile = path.join(STATE_DIR, 'last-snapshot.txt');
      const prev = fs.existsSync(prevFile) ? fs.readFileSync(prevFile, 'utf-8') : '';
      const page = await mp.currentPage();
      const current = await buildSnapshot(page, {});
      const diff = computeDiff(prev, current.snapshot);
      fs.writeFileSync(prevFile, current.snapshot);
      return { diff, current: current.snapshot };
    }

    case 'recordStart': {
      startRecording();
      return { ok: true };
    }

    case 'recordStop': {
      const outPath = stopRecording(params.output);
      return { ok: true, path: outPath };
    }

    default:
      throw new Error(`Unknown method: ${method}`);
  }
}

function computeDiff(a: string, b: string): string {
  const aLines = a.split('\n');
  const bLines = b.split('\n');
  const added = bLines.filter(l => !aLines.includes(l)).map(l => `+ ${l}`);
  const removed = aLines.filter(l => !bLines.includes(l)).map(l => `- ${l}`);
  if (added.length === 0 && removed.length === 0) return '(no changes)';
  return [...removed, ...added].join('\n');
}

function startServer(port: number) {
  ensureStateDir();

  const server = http.createServer(async (req, res) => {
    if (req.method !== 'POST' || req.url !== '/rpc') {
      res.writeHead(404);
      res.end('Not found');
      return;
    }

    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', async () => {
      let parsed: any;
      try {
        parsed = JSON.parse(body);
      } catch {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Invalid JSON' }));
        return;
      }

      const { method, params = {} } = parsed;
      try {
        const result = await handleRpc(method, params);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ result }));
      } catch (err: any) {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: err.message || String(err) }));
      }
    });
  });

  server.listen(port, '127.0.0.1', () => {
    fs.writeFileSync(PID_FILE, String(process.pid));
    console.log(`agent-mp daemon running on http://127.0.0.1:${port}`);
  });

  process.on('SIGTERM', () => {
    server.close();
    if (fs.existsSync(PID_FILE)) fs.unlinkSync(PID_FILE);
    process.exit(0);
  });

  process.on('SIGINT', () => {
    server.close();
    if (fs.existsSync(PID_FILE)) fs.unlinkSync(PID_FILE);
    process.exit(0);
  });
}

const port = parseInt(process.env.AGENT_MP_PORT || String(DEFAULT_PORT), 10);
startServer(port);
